apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-qa
spec:
  selector:
    app: maven-web-app-qa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
